### DISCUSSION TITLE
Stacked Bar: De-emphasize one of the bars?

### DISCUSSION THREAD

**Discussion by errantmind** [f5/unovis#244] [Q&A] [answered]
Hello,

I have a horizontal stacked bar chart with 3 bars. I'd like one of the bars (rightmost) to be de-emphasized as it is less important. One idea I had was to make the fill of the particular bar transparent with only a border. Another idea would be to have just a point marking the extent of the particular bar, instead of a bar. Are either of these feasible? Any other ideas?

**Comment by rokotyan** [comment]
@errantmind Yes, that's doable. You can apply some attribute to that bar by using currently undocumented `attributes` feature, and using it to apply certain style. Here's an example using React:

CSS:
```css
.chart g[fade] {
  fill-opacity: 0.25;
  --vis-grouped-bar-fill-color: none;
  --vis-grouped-bar-stroke-color: #985353;
  --vis-grouped-bar-stroke-width: 1px;
  stroke-dasharray: 2 2;
}
```

JSX:
```jsx
<VisXYContainer className=".chart" ...>
  <VisGroupedBar
    ...
    attributes={{
      [GroupedBar.selectors.barGroup]: {
        fade: (d, i) => i === 2 ? '' : null, // Apply the "fade" attribute to the third bar group
      },
  }}/>
   ...
</VisXYContainer>
```
<img width="353" alt="SCR-20230705-nphr" src="https://github.com/f5/unovis/assets/755708/d1c42779-4bbe-4c08-874f-34d6158069db"><img width="487" alt="SCR-20230705-nsyi" src="https://github.com/f5/unovis/assets/755708/12448272-7307-4a2f-8dda-275482c34a86">
